In [1]:
import pandas as pd

## Find Irainian Candidates

In [2]:
df_basics = pd.read_csv('../data/raw/title.basics.tsv.gz', sep='\t', low_memory=False)

In [4]:
df_akas = pd.read_csv('../data/raw/title.akas.tsv.gz', sep='\t', low_memory=False)

In [18]:
iran_candidates = df_akas[(df_akas['region'] == 'IR') & (df_akas['language'] == 'fa')]['titleId'].unique()

In [19]:
print(len(iran_candidates))

4503

In [20]:
region_counts = df_akas.groupby('titleId')['region'].nunique()
low_region_count = region_counts[region_counts <= 5].index

In [21]:
iran_titles_v3 = set(iran_candidates) & set(low_region_count) #intersection
print(len(iran_titles_v3))

1854

In [35]:
print(iran_titles_v3)

{'tt8114174', 'tt30128241', 'tt8347878', 'tt27757477', 'tt8348052', 'tt9591766', 'tt7510836', 'tt30990943', 'tt12063924', 'tt16764112', 'tt2970322', 'tt0382275', 'tt1847648', 'tt7903340', 'tt8988990', 'tt0292950', 'tt9031772', 'tt0400329', 'tt7247282', 'tt8394334', 'tt0253922', 'tt15258940', 'tt9105090', 'tt7440160', 'tt5260020', 'tt0049557', 'tt21426372', 'tt9121506', 'tt0068252', 'tt29134207', 'tt28523668', 'tt12985888', 'tt14309538', 'tt7694184', 'tt0830914', 'tt3605208', 'tt10987040', 'tt7512772', 'tt8461390', 'tt39902017', 'tt8870570', 'tt6886734', 'tt20752324', 'tt8386652', 'tt12221628', 'tt8221948', 'tt14986234', 'tt4801224', 'tt28106712', 'tt13561432', 'tt11388224', 'tt0167971', 'tt1508694', 'tt8037658', 'tt4818952', 'tt18926886', 'tt2461740', 'tt0282885', 'tt28655610', 'tt1822212', 'tt10456236', 'tt2816152', 'tt5463152', 'tt6590290', 'tt2286815', 'tt38973043', 'tt11349332', 'tt9454842', 'tt2548096', 'tt14629636', 'tt10280188', 'tt8042526', 'tt28676878', 'tt4498818', 'tt10591356', 'tt9764972', 'tt7900992', 'tt14419416', 'tt5376718', 'tt5512702', 'tt15151644', 'tt12596502', 'tt0490965', 'tt21265298', 'tt13340340', 'tt0263592', 'tt30985689', 'tt21218358', 'tt6068266', 'tt4635162', 'tt18553536', 'tt6126484', 'tt11257956', 'tt1525786', 'tt0318312', 'tt1283889', 'tt27835895', 'tt6081328', 'tt27722185', 'tt0048009', 'tt33480886', 'tt28006548', 'tt15364820', 'tt13928280', 'tt14097488', 'tt39792181', 'tt0830855', 'tt5203724', 'tt14478762', 'tt2631114', 'tt43697518', 'tt0121402', 'tt12367810', 'tt12025808', 'tt6208000', 'tt0243403', 'tt0317297', 'tt11564452', 'tt5811142', 'tt0783692', 'tt2700758', 'tt21364388', 'tt14928584', 'tt10445316', 'tt11691332', 'tt0122434', 'tt8411412', 'tt28480558', 'tt11773286', 'tt15687844', 'tt1954574', 'tt2709876', 'tt6126944', 'tt23732272', 'tt12084390', 'tt8348164', 'tt34321275', 'tt28514229', 'tt38525636', 'tt6645418', 'tt0322267', 'tt2161934', 'tt10291162', 'tt3716078', 'tt3077282', 'tt12789688', 'tt15541818', 'tt6219974', 'tt0243588', 'tt0225751', 'tt28804447', 'tt5994872', 'tt2451328', 'tt2627564', 'tt2121774', 'tt6126642', 'tt33132249', 'tt0289997', 'tt5993188', 'tt8037662', 'tt11656846', 'tt5791288', 'tt10439336', 'tt21818864', 'tt33504255', 'tt28523991', 'tt9899840', 'tt43704167', 'tt3219774', 'tt27011778', 'tt5228172', 'tt9752488', 'tt0370448', 'tt5874148', 'tt6839612', 'tt11027104', 'tt10724898', 'tt15326196', 'tt0217032', 'tt8006398', 'tt29064636', 'tt8841552', 'tt34318406', 'tt8025616', 'tt27056953', 'tt36596372', 'tt16088386', 'tt29719779', 'tt4620346', 'tt0158707', 'tt9034180', 'tt16116542', 'tt8149800', 'tt31639191', 'tt32670677', 'tt27817538', 'tt5200822', 'tt4242596', 'tt11709296', 'tt38353645', 'tt24221932', 'tt3547106', 'tt4092132', 'tt10829210', 'tt28495867', 'tt2120848', 'tt27924990', 'tt30759673', 'tt27866939', 'tt13906190', 'tt22084662', 'tt29339958', 'tt9077150', 'tt0312933', 'tt6880164', 'tt25785616', 'tt22864388', 'tt13357646', 'tt27208415', 'tt16584842', 'tt9643092', 'tt0434044', 'tt13742622', 'tt12834118', 'tt21358940', 'tt0490803', 'tt14166134', 'tt23711328', 'tt43598957', 'tt11552074', 'tt27132976', 'tt0075192', 'tt27276593', 'tt6288292', 'tt6242240', 'tt11185008', 'tt9870726', 'tt19396858', 'tt0168694', 'tt28821518', 'tt3131742', 'tt0336049', 'tt0182503', 'tt27729201', 'tt0354346', 'tt9294994', 'tt2700170', 'tt10763758', 'tt7245428', 'tt6851590', 'tt23843024', 'tt32214338', 'tt0140654', 'tt14179922', 'tt10914156', 'tt2734860', 'tt15328122', 'tt18350914', 'tt26605565', 'tt7128584', 'tt1753846', 'tt38491634', 'tt38632399', 'tt6244898', 'tt0125114', 'tt6215376', 'tt20446992', 'tt1999148', 'tt7208790', 'tt30469750', 'tt6611316', 'tt5996442', 'tt7222618', 'tt1203509', 'tt29815682', 'tt11346408', 'tt33477560', 'tt5882860', 'tt3758488', 'tt4546136', 'tt38501468', 'tt10580394', 'tt1998244', 'tt0293717', 'tt2760020', 'tt0158788', 'tt32628988', 'tt20131962', 'tt2058671', 'tt24512854', 'tt34384483', 'tt8555120', 'tt27941252', 'tt5143706', 'tt5325096', 'tt8027868', 'tt4760656', 'tt8870614', 'tt27885345', 'tt11770890', 'tt4532596', 'tt5657380', 'tt28490070', 'tt5463510', 'tt6580302', 'tt7719186', 'tt0470781', 'tt27950976', 'tt13803330', 'tt13569626', 'tt8116612', 'tt43644534', 'tt32609553', 'tt4595808', 'tt11777056', 'tt27208463', 'tt10171906', 'tt6826434', 'tt7563942', 'tt18297754', 'tt22804976', 'tt26775486', 'tt13736404', 'tt1103217', 'tt11771036', 'tt13830866', 'tt9223376', 'tt0914791', 'tt7390078', 'tt6224508', 'tt7901384', 'tt4908854', 'tt0791575', 'tt5169678', 'tt12223866', 'tt34439095', 'tt1727771', 'tt5032216', 'tt0409344', 'tt8051714', 'tt7893350', 'tt11507134', 'tt12235296', 'tt27618798', 'tt28490187', 'tt29143100', 'tt0047658', 'tt6169610', 'tt3257494', 'tt28517186', 'tt0810424', 'tt39970827', 'tt27352096', 'tt0068223', 'tt6137186', 'tt7513170', 'tt13227998', 'tt12747106', 'tt3541028', 'tt9124232', 'tt0287460', 'tt0182731', 'tt8011058', 'tt14562826', 'tt7969216', 'tt31465414', 'tt15046590', 'tt6841496', 'tt28803239', 'tt1765995', 'tt35930645', 'tt6220974', 'tt5334156', 'tt27744952', 'tt12546888', 'tt8660508', 'tt6218794', 'tt13802348', 'tt0184454', 'tt3673948', 'tt34717496', 'tt14504712', 'tt7336418', 'tt10698738', 'tt2025556', 'tt12392582', 'tt27746660', 'tt9675374', 'tt34330790', 'tt4847140', 'tt5994868', 'tt29711095', 'tt1945152', 'tt6211490', 'tt6169556', 'tt13652912', 'tt7903410', 'tt10533840', 'tt30589184', 'tt8318376', 'tt13550788', 'tt1303829', 'tt13813412', 'tt6205538', 'tt17074512', 'tt0344464', 'tt12238680', 'tt6273838', 'tt22530124', 'tt27819150', 'tt17633838', 'tt10401506', 'tt9843568', 'tt14833652', 'tt18548180', 'tt37833333', 'tt4247046', 'tt19813424', 'tt6224010', 'tt1896849', 'tt28300643', 'tt6215590', 'tt38787078', 'tt10828262', 'tt2358899', 'tt7704572', 'tt12252336', 'tt26212382', 'tt2671420', 'tt28655784', 'tt33059326', 'tt2605222', 'tt10786684', 'tt13008186', 'tt6704346', 'tt15732300', 'tt28187794', 'tt25435742', 'tt27827731', 'tt14515590', 'tt18284244', 'tt3095070', 'tt6406248', 'tt7563890', 'tt4003350', 'tt13577184', 'tt24218944', 'tt4163264', 'tt6239450', 'tt13813870', 'tt28236325', 'tt20420796', 'tt12235546', 'tt28260594', 'tt4424330', 'tt6282694', 'tt8147158', 'tt8866866', 'tt34821688', 'tt27827123', 'tt5999174', 'tt7222710', 'tt7227950', 'tt13802028', 'tt16979828', 'tt27843701', 'tt24248866', 'tt6127364', 'tt1949115', 'tt21808580', 'tt24765698', 'tt15711194', 'tt0290335', 'tt10575378', 'tt28285425', 'tt14845446', 'tt15669640', 'tt4818870', 'tt28077776', 'tt30334953', 'tt3127636', 'tt6353100', 'tt11387958', 'tt26739056', 'tt3719550', 'tt1646220', 'tt11192314', 'tt6206820', 'tt12838456', 'tt38066112', 'tt9214898', 'tt4578920', 'tt30343774', 'tt2279927', 'tt28635955', 'tt37444481', 'tt6126284', 'tt1291643', 'tt10439334', 'tt11401246', 'tt8450662', 'tt12279160', 'tt3084132', 'tt0857292', 'tt6209534', 'tt0096097', 'tt21983546', 'tt43704846', 'tt11182080', 'tt9316330', 'tt1514418', 'tt0385501', 'tt4246632', 'tt7321322', 'tt9818916', 'tt28035675', 'tt8979220', 'tt15826370', 'tt21201446', 'tt0182736', 'tt0780076', 'tt5643170', 'tt33057162', 'tt0382590', 'tt2248819', 'tt1598440', 'tt43589858', 'tt27524700', 'tt0183752', 'tt7488390', 'tt27421047', 'tt28575736', 'tt14571920', 'tt12235174', 'tt21115102', 'tt33888208', 'tt13795352', 'tt13760422', 'tt4593004', 'tt34614971', 'tt8125584', 'tt0826076', 'tt29041735', 'tt4910708', 'tt8111546', 'tt33295800', 'tt28821658', 'tt2957056', 'tt21914488', 'tt4015888', 'tt6840694', 'tt1047490', 'tt3719198', 'tt9160100', 'tt5142178', 'tt11481270', 'tt5634018', 'tt21142392', 'tt0391233', 'tt7307392', 'tt13696578', 'tt12831286', 'tt0263260', 'tt3507794', 'tt17297488', 'tt27163098', 'tt7780248', 'tt2161896', 'tt2627624', 'tt6243086', 'tt1600756', 'tt36100557', 'tt14612164', 'tt19800508', 'tt8555228', 'tt8011462', 'tt14739092', 'tt28236277', 'tt32105664', 'tt9364396', 'tt28638474', 'tt0197332', 'tt3510520', 'tt10374242', 'tt28510326', 'tt7326418', 'tt9522226', 'tt6145582', 'tt0182753', 'tt11787536', 'tt20117876', 'tt33079121', 'tt21264074', 'tt32144066', 'tt7231182', 'tt10312990', 'tt31146329', 'tt6330268', 'tt1363485', 'tt8126228', 'tt6215588', 'tt24784906', 'tt1175306', 'tt0820872', 'tt28480249', 'tt6261448', 'tt24695696', 'tt38236231', 'tt0169580', 'tt0319640', 'tt0064368', 'tt15483528', 'tt31490696', 'tt7336382', 'tt7841412', 'tt2671388', 'tt5797456', 'tt8377736', 'tt38808503', 'tt12238064', 'tt6831812', 'tt0046779', 'tt0316935', 'tt13387200', 'tt0839762', 'tt0405720', 'tt1726583', 'tt9160082', 'tt20860924', 'tt13567492', 'tt21115208', 'tt28527948', 'tt35927913', 'tt39974793', 'tt0419955', 'tt10925824', 'tt13491872', 'tt2258651', 'tt13935784', 'tt15020050', 'tt7657840', 'tt11588714', 'tt6209994', 'tt13357022', 'tt5217976', 'tt26772087', 'tt27930635', 'tt1104082', 'tt27518922', 'tt4008544', 'tt27228368', 'tt28378575', 'tt8026328', 'tt7241928', 'tt5192374', 'tt23143220', 'tt11815434', 'tt0340374', 'tt8551514', 'tt10438636', 'tt12247574', 'tt7971994', 'tt28092668', 'tt14214846', 'tt13711328', 'tt13939102', 'tt15311876', 'tt1895589', 'tt25177422', 'tt26750621', 'tt22871222', 'tt28142753', 'tt3441780', 'tt9354450', 'tt1522811', 'tt14837302', 'tt30747080', 'tt28028517', 'tt13873178', 'tt28078109', 'tt8686878', 'tt14376166', 'tt10575396', 'tt12235770', 'tt22872188', 'tt3820728', 'tt9149508', 'tt12600806', 'tt2892230', 'tt0872184', 'tt18335404', 'tt2322572', 'tt8870592', 'tt10231358', 'tt20116592', 'tt0269826', 'tt6290600', 'tt6841602', 'tt5592814', 'tt4966418', 'tt28740897', 'tt27936720', 'tt30235828', 'tt4079782', 'tt3416476', 'tt7967752', 'tt36132781', 'tt7904520', 'tt26458288', 'tt28512118', 'tt14987150', 'tt1043694', 'tt21438474', 'tt7201596', 'tt6393234', 'tt12158396', 'tt0107193', 'tt13534806', 'tt21227066', 'tt19753674', 'tt0439477', 'tt23833430', 'tt37442782', 'tt27747416', 'tt27908305', 'tt38777676', 'tt8148198', 'tt0182673', 'tt3314454', 'tt10133210', 'tt12235374', 'tt1260694', 'tt5897428', 'tt38594116', 'tt2297706', 'tt7188250', 'tt20159142', 'tt6065024', 'tt8866676', 'tt10426860', 'tt11102282', 'tt2173366', 'tt2612226', 'tt0111844', 'tt0194087', 'tt27263209', 'tt9899880', 'tt8352378', 'tt26745135', 'tt27923060', 'tt7166300', 'tt28774761', 'tt4493272', 'tt1104051', 'tt3138188', 'tt15482570', 'tt2465646', 'tt27600109', 'tt26753080', 'tt8276568', 'tt29489822', 'tt5755594', 'tt28350068', 'tt8460746', 'tt28870722', 'tt29942156', 'tt38069222', 'tt24873336', 'tt0293111', 'tt12438950', 'tt33292056', 'tt27881517', 'tt0150630', 'tt5141848', 'tt28023356', 'tt21370992', 'tt12422524', 'tt34380109', 'tt7700742', 'tt1521081', 'tt0791478', 'tt2083354', 'tt16173258', 'tt0487894', 'tt7350876', 'tt0046893', 'tt7634654', 'tt0064798', 'tt0294848', 'tt5238648', 'tt9334630', 'tt0183154', 'tt10822466', 'tt8816262', 'tt13799838', 'tt0996598', 'tt15754788', 'tt3667264', 'tt8863964', 'tt2246945', 'tt10588878', 'tt43649956', 'tt11576058', 'tt0144474', 'tt9643058', 'tt1667121', 'tt10592466', 'tt6693930', 'tt33512163', 'tt19897990', 'tt27797666', 'tt10908138', 'tt0441092', 'tt0277275', 'tt5216606', 'tt26453835', 'tt10354764', 'tt15929228', 'tt27820199', 'tt7526594', 'tt8088804', 'tt13928356', 'tt0801349', 'tt30054226', 'tt14745948', 'tt27331142', 'tt7169078', 'tt9042288', 'tt8661084', 'tt10585918', 'tt7385140', 'tt8442002', 'tt6213794', 'tt27850891', 'tt18340522', 'tt7329128', 'tt1104085', 'tt1933620', 'tt11729218', 'tt26757504', 'tt17685714', 'tt12587650', 'tt3507558', 'tt27503091', 'tt13580888', 'tt31463201', 'tt12229534', 'tt1300571', 'tt13529512', 'tt20856142', 'tt3820326', 'tt19811986', 'tt3644204', 'tt1982734', 'tt2089764', 'tt23119480', 'tt0060093', 'tt14419028', 'tt6217848', 'tt6127026', 'tt13736508', 'tt5518340', 'tt0345399', 'tt28499893', 'tt9086598', 'tt13885690', 'tt27374498', 'tt3898912', 'tt13181898', 'tt2338337', 'tt31095111', 'tt6291518', 'tt0459985', 'tt12238000', 'tt0454808', 'tt8147080', 'tt0320430', 'tt34688215', 'tt0182675', 'tt4242866', 'tt34389291', 'tt28082097', 'tt6851202', 'tt28515342', 'tt11673636', 'tt28630321', 'tt34571787', 'tt26343462', 'tt6687972', 'tt27205439', 'tt7100588', 'tt0414302', 'tt0302330', 'tt20258156', 'tt10579782', 'tt4607424', 'tt6840802', 'tt26896053', 'tt14687028', 'tt34702824', 'tt33483713', 'tt28758568', 'tt3216126', 'tt34548428', 'tt38056315', 'tt19767866', 'tt26697468', 'tt13795618', 'tt16166054', 'tt12861832', 'tt2691540', 'tt0495768', 'tt10724162', 'tt6217474', 'tt6275138', 'tt12453066', 'tt20564540', 'tt28208445', 'tt6661850', 'tt0939921', 'tt34245419', 'tt28511592', 'tt27862274', 'tt28812407', 'tt6269918', 'tt14599566', 'tt28352669', 'tt2133304', 'tt0331527', 'tt15075168', 'tt2338367', 'tt27518057', 'tt3131732', 'tt38940199', 'tt13728840', 'tt23985694', 'tt8870126', 'tt0429756', 'tt26740828', 'tt8277138', 'tt15809726', 'tt31998398', 'tt2246629', 'tt22802220', 'tt0282267', 'tt1863384', 'tt6841582', 'tt27953920', 'tt3248764', 'tt21160386', 'tt0208709', 'tt28479081', 'tt2998404', 'tt0319492', 'tt34748080', 'tt4837182', 'tt34597242', 'tt6242134', 'tt13671872', 'tt13514852', 'tt8248934', 'tt22326592', 'tt8623884', 'tt8428726', 'tt7967006', 'tt28221138', 'tt8280674', 'tt0318147', 'tt13096500', 'tt4247084', 'tt7228134', 'tt34382204', 'tt10659416', 'tt11773160', 'tt28133994', 'tt28364755', 'tt13120494', 'tt1847622', 'tt0280898', 'tt6028758', 'tt27167025', 'tt7909688', 'tt1354055', 'tt28108792', 'tt0793586', 'tt1152271', 'tt4253460', 'tt8351514', 'tt35706435', 'tt8085390', 'tt7761536', 'tt29043207', 'tt34293923', 'tt7897154', 'tt5897312', 'tt25237358', 'tt0311583', 'tt8374162', 'tt0459011', 'tt24215176', 'tt10052314', 'tt35661615', 'tt7902900', 'tt34380467', 'tt12662544', 'tt13637414', 'tt8189036', 'tt5766064', 'tt12094102', 'tt11616216', 'tt13802234', 'tt5658296', 'tt12121712', 'tt11341310', 'tt0080087', 'tt27470873', 'tt6219484', 'tt15188158', 'tt6149830', 'tt2433014', 'tt28100983', 'tt14837298', 'tt27490334', 'tt5836670', 'tt7985654', 'tt27192607', 'tt10151968', 'tt5761114', 'tt6393474', 'tt9034706', 'tt10908228', 'tt11771204', 'tt16770064', 'tt14760850', 'tt5991486', 'tt12350736', 'tt11027072', 'tt43652041', 'tt28797705', 'tt8143764', 'tt26349306', 'tt6281266', 'tt11280588', 'tt7563932', 'tt36271386', 'tt0243535', 'tt2128569', 'tt23841402', 'tt27859695', 'tt20863616', 'tt11585790', 'tt27923734', 'tt1111905', 'tt27844001', 'tt9409768', 'tt14412866', 'tt4242850', 'tt19894700', 'tt11122430', 'tt3660472', 'tt3212802', 'tt1295075', 'tt9310920', 'tt23942136', 'tt0184284', 'tt14395518', 'tt0049375', 'tt3688798', 'tt4730108', 'tt30768293', 'tt5526894', 'tt11012820', 'tt0183874', 'tt6158400', 'tt27096768', 'tt10488892', 'tt12158652', 'tt27696780', 'tt6857852', 'tt2638018', 'tt0319401', 'tt2278052', 'tt8168818', 'tt1204953', 'tt11714790', 'tt4488600', 'tt0431487', 'tt12235014', 'tt10482096', 'tt15067334', 'tt7865560', 'tt15428534', 'tt6938316', 'tt6469338', 'tt5623888', 'tt38566766', 'tt3605152', 'tt9827574', 'tt4080008', 'tt7203412', 'tt5243278', 'tt0399850', 'tt7097110', 'tt22805048', 'tt0438244', 'tt2551076', 'tt0048935', 'tt33483828', 'tt12993100', 'tt0484528', 'tt10592390', 'tt10631470', 'tt27860948', 'tt3409370', 'tt12736362', 'tt21230908', 'tt2906272', 'tt5214306', 'tt27846113', 'tt0079841', 'tt27301247', 'tt12518278', 'tt0429567', 'tt10783986', 'tt12244618', 'tt8346906', 'tt7179112', 'tt6242216', 'tt8870036', 'tt7927770', 'tt12235120', 'tt9510454', 'tt10290986', 'tt13800880', 'tt28486289', 'tt30021494', 'tt0155874', 'tt1572492', 'tt26258278', 'tt9023654', 'tt2349630', 'tt11845700', 'tt3486358', 'tt9455230', 'tt11576698', 'tt27406652', 'tt12221548', 'tt28298071', 'tt35679269', 'tt28692851', 'tt33256382', 'tt0099392', 'tt13456598', 'tt5860270', 'tt0283954', 'tt1808364', 'tt38590238', 'tt11374160', 'tt11591834', 'tt27862079', 'tt8823378', 'tt9451744', 'tt38525303', 'tt0052321', 'tt0111425', 'tt6949578', 'tt34380118', 'tt28667635', 'tt29272099', 'tt39300968', 'tt10959384', 'tt12270046', 'tt27862795', 'tt0934786', 'tt34386714', 'tt6240914', 'tt22180090', 'tt5940882', 'tt1933566', 'tt1382262', 'tt33485500', 'tt23730024', 'tt6281320', 'tt0121973', 'tt15034976', 'tt7929642', 'tt13321312', 'tt30146745', 'tt28429950', 'tt28792795', 'tt30228234', 'tt33770511', 'tt0080848', 'tt6203694', 'tt28367711', 'tt7692968', 'tt14927284', 'tt18364680', 'tt18228202', 'tt35603969', 'tt2040569', 'tt18328936', 'tt1849224', 'tt13075418', 'tt38855137', 'tt15139584', 'tt0066742', 'tt6221938', 'tt12698500', 'tt16283022', 'tt2038245', 'tt9642950', 'tt10579686', 'tt8866888', 'tt0123046', 'tt6237562', 'tt3540420', 'tt6871390', 'tt4849528', 'tt0344497', 'tt10797718', 'tt27389663', 'tt8629094', 'tt27390813', 'tt15157194', 'tt30970601', 'tt38701435', 'tt9079836', 'tt3409362', 'tt36208382', 'tt28309364', 'tt4175264', 'tt5423636', 'tt38517267', 'tt32840744', 'tt7902726', 'tt39227599', 'tt27727572', 'tt5537400', 'tt14176552', 'tt18116126', 'tt16755052', 'tt3658010', 'tt2218011', 'tt14796508', 'tt20604342', 'tt27412095', 'tt16240096', 'tt34538577', 'tt10579828', 'tt8748698', 'tt7899984', 'tt0382579', 'tt5994870', 'tt2256706', 'tt7383920', 'tt28535699', 'tt3724978', 'tt2250524', 'tt38048001', 'tt0344083', 'tt5897102', 'tt12269828', 'tt28630581', 'tt34347067', 'tt38845678', 'tt22817592', 'tt21188642', 'tt11186784', 'tt19245950', 'tt2367034', 'tt21943306', 'tt7897086', 'tt3714412', 'tt13571152', 'tt24315528', 'tt11657454', 'tt0129950', 'tt9403944', 'tt2338207', 'tt5019778', 'tt6272398', 'tt19894546', 'tt2575080', 'tt29115340', 'tt27390832', 'tt27459609', 'tt8874308', 'tt13509824', 'tt9217626', 'tt7935018', 'tt43562869', 'tt13117176', 'tt13563300', 'tt13654752', 'tt2104962', 'tt29249702', 'tt37052238', 'tt15206298', 'tt8289604', 'tt6218740', 'tt10579792', 'tt21359846', 'tt14349128', 'tt6217748', 'tt10079882', 'tt34674527', 'tt16059142', 'tt14239092', 'tt8465094', 'tt15123564', 'tt30146989', 'tt23464606', 'tt13662022', 'tt7825602', 'tt3212670', 'tt16911980', 'tt0317822', 'tt12856038', 'tt20378354', 'tt13653022', 'tt20415200', 'tt11773814', 'tt18297746', 'tt27827415', 'tt0044728', 'tt9347682', 'tt19370042', 'tt12292210', 'tt6867578', 'tt27931034', 'tt7527876', 'tt0158947', 'tt21963570', 'tt6495522', 'tt7166170', 'tt9173924', 'tt12238152', 'tt0188054', 'tt8144694', 'tt32780082', 'tt13911188', 'tt35653619', 'tt27272543', 'tt20421178', 'tt15017986', 'tt1569369', 'tt14690380', 'tt7127956', 'tt6173368', 'tt7611812', 'tt7897212', 'tt1786476', 'tt27737258', 'tt28484796', 'tt6207032', 'tt2301165', 'tt7887012', 'tt13624016', 'tt15169998', 'tt2247063', 'tt9293926', 'tt9210424', 'tt14934674', 'tt10954028', 'tt43350976', 'tt2081259', 'tt2937854', 'tt0100734', 'tt8130734', 'tt8000708', 'tt1392227', 'tt27641352', 'tt2660842', 'tt6593476', 'tt14337230', 'tt8884310', 'tt7901122', 'tt26680515', 'tt6952680', 'tt7152146', 'tt9169166', 'tt38083416', 'tt4634290', 'tt4663708', 'tt11268562', 'tt0348171', 'tt2613288', 'tt1964988', 'tt3209260', 'tt3820086', 'tt2040342', 'tt6217816', 'tt0877591', 'tt2691726', 'tt8842350', 'tt12267412', 'tt7192212', 'tt27164894', 'tt6221930', 'tt12735456', 'tt2914020', 'tt5881460', 'tt9844772', 'tt6855042', 'tt13217680', 'tt6607602', 'tt9119756', 'tt2244949', 'tt2247053', 'tt35205646', 'tt4153358', 'tt10168462', 'tt28654249', 'tt16239160', 'tt8470090', 'tt5216604', 'tt36777955', 'tt8809576', 'tt8998916', 'tt12438936', 'tt11591652', 'tt12865956', 'tt3967508', 'tt7385132', 'tt7762434', 'tt7483288', 'tt21080366', 'tt2670642', 'tt7111402', 'tt7799740', 'tt11687210', 'tt10579734', 'tt35403122', 'tt9731048', 'tt10150348', 'tt1786493', 'tt6242224', 'tt7900518', 'tt3067938', 'tt19939364', 'tt10584722', 'tt5256996', 'tt6291584', 'tt8348064', 'tt0978609', 'tt7791926', 'tt6935840', 'tt1764298', 'tt8390150', 'tt10059220', 'tt10106844', 'tt5838908', 'tt10438484', 'tt4169580', 'tt5650614', 'tt12234504', 'tt1151370', 'tt23810584', 'tt1099199', 'tt28223115', 'tt27050940', 'tt3586582', 'tt9357044', 'tt7900928', 'tt10991370', 'tt7762444', 'tt5214300', 'tt0084188', 'tt5390232', 'tt9872488', 'tt32298681', 'tt0439889', 'tt7527778', 'tt12111496', 'tt28208753', 'tt5915824', 'tt27752043', 'tt10575714', 'tt1826847', 'tt30811240', 'tt18264676', 'tt

In [22]:
iran_basics = df_basics[df_basics['tconst'].isin(iran_titles_v3)]
iran_basics['titleType'].value_counts()

titleType
movie           986
short           463
tvSeries        233
tvMovie          75
video            47
tvMiniSeries     36
videoGame         8
tvSpecial         4
tvShort           2
Name: count, dtype: int64

In [23]:
selected_types = ['movie', 'tvSeries', 'tvMovie', 'tvMiniSeries']
iranian_tconst = df_basics[df_basics['tconst'].isin(iran_titles_v3) & df_basics['titleType'].isin(selected_types)]
iran_tconst_set = set(iranian_tconst['tconst'])
print("final Irainian set of films: ", len(iran_tconst_set))

final Irainian set of films:  1330

In [24]:
chunks = []
for chunk in pd.read_csv('../data/raw/title.principals.tsv.gz', sep='\t', chunksize=1_000_000, low_memory=False):
    filtered = chunk[chunk['tconst'].isin(iran_tconst_set)]
    chunks.append(filtered)

df_principals_iran = pd.concat(chunks, ignore_index=True)

df_merged = iranian_tconst.merge(df_principals_iran, on='tconst', how='inner')
print(df_merged.shape)
df_merged.head()

(17107, 14)

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres,ordering,nconst,category,job,characters
0,tt0044728,movie,Huracán Ramírez,Huracán Ramírez,0,1953,\N,103,"Action,Comedy,Crime",1,nm0798270,actor,\N,"[""Fernando Torres (Huracán Ramírez)""]"
1,tt0044728,movie,Huracán Ramírez,Huracán Ramírez,0,1953,\N,103,"Action,Comedy,Crime",2,nm0739131,actress,\N,"[""Margarita""]"
2,tt0044728,movie,Huracán Ramírez,Huracán Ramírez,0,1953,\N,103,"Action,Comedy,Crime",3,nm0327643,actress,\N,"[""Laura""]"
3,tt0044728,movie,Huracán Ramírez,Huracán Ramírez,0,1953,\N,103,"Action,Comedy,Crime",4,nm0273508,actor,\N,"[""El pichi""]"
4,tt0044728,movie,Huracán Ramírez,Huracán Ramírez,0,1953,\N,103,"Action,Comedy,Crime",5,nm0414109,actor,\N,"[""Señor Torres (Tonina Jackson)""]"

In [15]:
# saved df_merged on hard disk to use later 
import os
os.makedirs('../data/processed', exist_ok=True)
df_merged.to_parquet('../data/processed/iran_films_principals.parquet')
print("saved: ", df_merged.shape)

saved:  (92518, 14)

In [47]:
df_akas[df_akas['titleId'] == 'tt0044728']

,titleId,ordering,title,region,language,types,attributes,isOriginalTitle
417152,tt0044728,1,Huracán Ramírez,\N,\N,original,\N,1
417153,tt0044728,2,Huracán Ramírez,BR,\N,imdbDisplay,\N,0
417154,tt0044728,3,Huracán Ramírez,MX,\N,imdbDisplay,\N,0
417155,tt0044728,4,Qahremane shekastnapazir,IR,fa,imdbDisplay,\N,0